export const projects = [
  {
    name: "フリーランスホームページ",
    githubUrl: "",
    image: "/assets/projects/1.png",
    category: ["react", "aws"],
  },
  {
    name: "働き方メディア",
    githubUrl: "",
    image: "/assets/projects/2.png",
    category: ["react", "aws"],
  },
  {
    name: "マーケティング戦略",
    githubUrl: "",
    image: "/assets/projects/3.png",
    category: ["react", "aws"],
  },
  {
    name: "学生向けメディア",
    githubUrl: "",
    image: "/assets/projects/4.png",
    category: ["react"],
    projectUrl: "",
    deployed: true,
  },
  {
    name: "ビジネスランディングページ",
    githubUrl: "",
    image: "/assets/projects/5.png",
    category: ["react"],
  },
  {
    name: "ポートフォリオ",
    githubUrl: "",
    image: "/assets/projects/6.png",
    category: ["wordpress"],
    projectUrl: "",
    deployed: true,
  },
  {
    name: "化粧品メディア",
    githubUrl: "",
    image: "/assets/projects/7.png",
    category: ["react"],
    projectUrl: "",
    deployed: true,
  },
  {
    name: "ブログメディア",
    githubUrl: "",
    image: "/assets/projects/8.png",
    category: ["react"],
    projectUrl: "",
    deployed: true,
  },
  {
    name: "商品紹介",
    githubUrl: "",
    image: "/assets/projects/9.png",
    category: ["wordpress"],
    projectUrl: "",
    deployed: true,
  },
  {
    name: "企業ホームページ",
    githubUrl: "",
    image: "/assets/projects/10.png",
    category: ["react"],
    projectUrl: "",
    deployed: true,
  },
  {
    name: "ネット配信ページ",
    githubUrl: "",
    image: "/assets/projects/11.png",
    category: ["wordpress"],
  },
  {
    name: "文化祭ページ",
    githubUrl: "",
    image: "/assets/projects/12.png",
    category: ["react"],
  },
];
